apiVersion: v1
kind: Service
metadata:
  name: visionmongo
  namespace: default
  labels:
    app: visionmongo
spec:
  selector:
    app: visionmongo
  type: LoadBalancer
  ports:
    - name: http
      port: 8080
